title: "{hackpac}"
baseurl: ""

date_format: "%Y-%m-%d"

google_analytics:
disqus_shortname:
theme: jekyll-theme-cayman

# Build settings
kramdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
